name: ci-diif

on: [push]

jobs:
  ci-diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: install
      run: |
        pip3 install --upgrade pip
        make install
    - name: test
      run: |
        make install-dev
        make diff-test
